name: road_saver
description: "A Flutter application for roadside assistance."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  firebase_in_app_messaging: ^0.8.1+6
  firebase_remote_config: ^5.2.3
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^19.2.1
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconn.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/iconn.png"
  adaptive_icon_background: "#000000"